
language: python

python:
  - "3.6"

script:
  - py.test -rxs --cov varg/ tests/

install:
  - pip install -r requirements.txt -r requirements-dev.txt -e .

notifications:
  email: false

after_success:
  - coveralls
