---

name: Publish to Docker Hub

"on":
  release:
      types: [published]
  push:
    tags:
      - '*'
jobs:
  docker-image-CI:
   name: Docker Image CI
   runs-on: ubuntu-latest
   steps:
    - name: Check out git repository
      uses: actions/checkout@v2
    - name: Publish to Registry
      pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: clinicalgenomics/varg
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"